# Generated by Django 2.1.2 on 2018-10-08 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70, verbose_name='título')),
                ('carta', models.ImageField(upload_to='cartas/', verbose_name='imagem da carta')),
                ('numero', models.IntegerField(blank=True, verbose_name='número da carta')),
                ('cor', models.IntegerField(blank=True, choices=[(0, 'Vermelho'), (1, 'Amarelo'), (2, 'Verde'), (3, 'Azul')], verbose_name='cor da carta')),
                ('inverso', models.IntegerField(choices=[(0, 'Sim'), (1, 'Não')], verbose_name='inverter jogo')),
                ('comprar2', models.IntegerField(choices=[(0, 'Sim'), (1, 'Não')], verbose_name='comprar +2')),
                ('comprar4', models.IntegerField(choices=[(0, 'Sim'), (1, 'Não')], verbose_name='comprar +4')),
                ('bloqueio', models.IntegerField(choices=[(0, 'Sim'), (1, 'Não')], verbose_name='bloqueio')),
            ],
            options={
                'verbose_name': 'carta',
                'verbose_name_plural': 'cartas',
            },
        ),
        migrations.CreateModel(
            name='CartaDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Não Usada'), (1, 'Usada')], verbose_name='status')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='jogo.Carta', verbose_name='carta')),
            ],
            options={
                'verbose_name': 'carta do deck',
                'verbose_name_plural': 'cartas dos decks',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartas', models.ManyToManyField(blank=True, related_name='cards', to='jogo.CartaDeck', verbose_name='cartas')),
            ],
            options={
                'verbose_name': 'deck',
                'verbose_name_plural': 'decks',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_jogadores', models.IntegerField(verbose_name='quantidade de jogadores')),
                ('status', models.IntegerField(choices=[(0, 'Aguardando Jogadores'), (1, 'Em Andamento'), (2, 'Finalizada')], verbose_name='Status')),
                ('jogadores', models.ManyToManyField(blank=True, related_name='jogadores', to=settings.AUTH_USER_MODEL, verbose_name='jogadores')),
                ('turno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL, verbose_name='jogador atual')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'partida',
                'verbose_name_plural': 'partidas',
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida', to='jogo.Partida', verbose_name='partida'),
        ),
        migrations.AddField(
            model_name='deck',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
