# Generated by Django 2.1.2 on 2018-10-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_auto_20181008_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='last_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_cards', to='jogo.CartaDeck', verbose_name='última carta jogada'),
        ),
    ]
